
import java.rmi.Naming;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ADMIN
 */
public class Myclientchuyentien extends javax.swing.JFrame {

    /**
     * Creates new form Myclientchuyentien
     */
    private String stk;
    public Myclientchuyentien(String stk) {
        initComponents();
        this.stk=stk;
       
    }
    public class Xuly extends Thread {

        public void run() {
            try {
                ITinhToankt server = (ITinhToankt) Naming.lookup("rmi://" + "192.168.1.3" + "/TinhToankt");
                String sd = server.timstk(stk);
                txtsodu.setText(sd);
                LocalDate dateNow = LocalDate.now();
                String ngayChuyenTien= server.getNgayChuyenTien(stk);
                String dateString = dateNow.toString();
                if(ngayChuyenTien.equals(dateString)){
                     System.out.println("Hai chuỗi ngày giống nhau.");
                }else{
                    server.setChuyenTien(stk,0);
                }
            } catch (Exception loi) {
                loi.printStackTrace();
            }
        }
    }

    
    Myclientchuyentien() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtstchuyen = new javax.swing.JTextField();
        txtstkc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtsodu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txtten = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btncancel = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txtstchuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstchuyenActionPerformed(evt);
            }
        });
        txtstchuyen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtstchuyenKeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel1.setText("Nhập STK cần chuyển:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel2.setText("Nhập số tiền cần chuyển: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel3.setText("Số dư:");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton1.setText("Chuyển tiền");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Quay lại");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel4.setText("CHUYỂN TIỀN");

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton3.setText("Nạp tên");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel5.setText("Tên chủ thẻ:");

        btncancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btncancel.setText("Cancel");
        btncancel.setActionCommand("");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("( Nhấn Ok để rút tiền hoặc Cancel để hủy bỏ )");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtten, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtstkc, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtstchuyen)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 23, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtsodu, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(44, 44, 44))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton2)
                                        .addGap(75, 75, 75)
                                        .addComponent(jLabel4)))))
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(jButton1)
                                .addGap(9, 9, 9)))))
                .addGap(66, 66, 66))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsodu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtstkc, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtten, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtstchuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btncancel))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
                  Xuly xl=new Xuly();
                    xl.start();
        
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        try {
            ITinhToankt server = (ITinhToankt) Naming.lookup("rmi://" + "192.168.1.3" + "/TinhToankt");              
            String stkc = txtstkc.getText();
            String sotiencText = txtstchuyen.getText();
            String tennguoinhan = txtten.getText();
            //Lay so tien gioi han chyen trong ngày  
            
            String gioiHanTienText=server.getGioiHanTien(stk);
            long gioiHanTien=Long.parseLong(gioiHanTienText);
            

            // Kiểm tra sotiencText có rỗng không
            if (sotiencText.isEmpty() || stkc.isEmpty() || tennguoinhan.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!");
            } else {
                
                    long sotienc = Long.parseLong(sotiencText);
                    
                    String soduText = txtsodu.getText();
                    long sodu = Long.parseLong(soduText);
                    
                    String sodunguoinhan= server.timstk(stkc);
                    long sdnguoinhan = Long.parseLong(sodunguoinhan);
                    
                                       
                    if (sotienc >= 50000&&sotienc<=5000000) {
                        if (sotienc > sodu) {
                            JOptionPane.showMessageDialog(this, "Số dư không đủ!");
                        } else {
                            long tongTienNgay=sotienc+gioiHanTien;
                           if(tongTienNgay<=30000000){
                               long dsmchuthe= sodu-sotienc;
                            server.setSoDu(stk, dsmchuthe);
                            
                            long dsmnguoinha= sdnguoinhan+sotienc;
                            server.setSoDu(stkc, dsmnguoinha);
                            
                            server.setHoaDon(stk, "Chuyen tien den", sotienc, stkc);
                            server.setHoaDon(stkc, "Nhan tien tu", sotienc, stk);
                            server.setChuyenTien(stk, tongTienNgay);
                            JOptionPane.showMessageDialog(this, "Giao dịch thành công!");
                            String sdu = server.timstk(stk);
                           
                            txtsodu.setText(sdu);
                            txtstchuyen.setText("");
                            
                           }else {
                               JOptionPane.showMessageDialog(this,"Giao dịch của bạn vượt mức hạn cho phép trong ngày!");
                           }
                            
                            
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Số tiền KHÔNG hợp lệ!");
                    }
                

            }
        } catch (Exception loi) {
            loi.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         this.dispose();
        Myclientmenu f = new Myclientmenu(this.stk);
        f.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtstchuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstchuyenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstchuyenActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
                
        try { 
                ITinhToankt server =(ITinhToankt) Naming.lookup("rmi://"+"192.168.1.3"+"/TinhToankt");
                String stkc = txtstkc.getText();
                String tentk= server.gettentk(stkc);
                if(tentk==null){
                    JOptionPane.showMessageDialog(this, "Số tài khoản KHÔNG tồn tại!");
                }else{
                    if(stkc.equals(stk)){
                        JOptionPane.showMessageDialog(this, "Tài khoản nguồn và tài hưởng thụ trùng nhau. Qúy khách vui lòng kiểm tra lại!");
                    }else{
                        txtten.setText(tentk);
                    }
                     
                }
                               

        } catch (Exception loi) {
            loi.printStackTrace();
        } 
       
                
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtstchuyenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtstchuyenKeyTyped
            char c=evt.getKeyChar();
            if(!Character.isDigit(c)){
                evt.consume();
            }
    }//GEN-LAST:event_txtstchuyenKeyTyped

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        try {
            ITinhToankt server = (ITinhToankt) Naming.lookup("rmi://" + "192.168.0.60" + "/TinhToankt");

            int choice = JOptionPane.showConfirmDialog(
                null,
                "Bạn có muốn tiếp tục thực hiện giao dịch nữa không?",
                "Xác nhận",
                JOptionPane.YES_NO_OPTION);

            if (choice == JOptionPane.NO_OPTION) {
                server.setTrangThaiTrue(stk);
                System.exit(0);
                // Thoát khỏi ứng dụng
            }

        } catch (Exception loi) {
            loi.printStackTrace();
        }
    }//GEN-LAST:event_btncancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Myclientchuyentien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Myclientchuyentien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Myclientchuyentien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Myclientchuyentien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Myclientchuyentien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtsodu;
    private javax.swing.JTextField txtstchuyen;
    private javax.swing.JTextField txtstkc;
    private javax.swing.JTextField txtten;
    // End of variables declaration//GEN-END:variables
}
