
import java.rmi.Naming;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ADMIN
 */
public class Myclientruttien extends javax.swing.JFrame {

    /**
     * Creates new form Myclientruttien
     */
    private String stk;
    public Myclientruttien(String stk) {
        initComponents();
        this.stk=stk;
    }
       public class Xuly extends Thread {
        public void run() {
            try {  
                ITinhToankt server = (ITinhToankt) Naming.lookup("rmi://"+"192.168.1.3"+"/TinhToankt");            
                String sd= server.timstk(stk);
                txtsodu.setText(sd); 
                LocalDate dateNow = LocalDate.now();
                String ngay= server.getNgay(stk);
                String dateString = dateNow.toString();
                System.out.println(ngay);
                if(ngay.equals(dateString)){
                     System.out.println("Hai chuỗi ngày giống nhau.");
                }else{
                    server.setGioiHan(stk,0);
                }
            System.out.println(ngay);
                               
            } catch (Exception loi) {
               loi.printStackTrace();
            } 
        }
    }
    private Myclientruttien() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtsotien = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtsodu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton6_200 = new javax.swing.JButton();
        jButton7_100 = new javax.swing.JButton();
        jButton8_500 = new javax.swing.JButton();
        jButton9_1000 = new javax.swing.JButton();
        jButton10_3000 = new javax.swing.JButton();
        jButton11_5000 = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 27)); // NOI18N
        jLabel1.setText("RÚT TIỀN");

        jButton1.setText("Quay lại");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtsotien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsotienKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Nhập số tiền cần rút:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Số dư:");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Ok");
        jButton2.setToolTipText("");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("VND ( Việt Nam Đồng )");

        jButton6_200.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton6_200.setText("200.000");
        jButton6_200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6_200ActionPerformed(evt);
            }
        });

        jButton7_100.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton7_100.setText("100.000");
        jButton7_100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7_100ActionPerformed(evt);
            }
        });

        jButton8_500.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton8_500.setText("500.000");
        jButton8_500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8_500ActionPerformed(evt);
            }
        });

        jButton9_1000.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton9_1000.setText("1.000.000");
        jButton9_1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9_1000ActionPerformed(evt);
            }
        });

        jButton10_3000.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton10_3000.setText("3.000.000");
        jButton10_3000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10_3000ActionPerformed(evt);
            }
        });

        jButton11_5000.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton11_5000.setText("5.000.000");
        jButton11_5000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11_5000ActionPerformed(evt);
            }
        });

        btncancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btncancel.setText("Cancel");
        btncancel.setActionCommand("");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("( Nhấn Ok để rút tiền hoặc Cancel để hủy bỏ )");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton7_100, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton6_200, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(63, 63, 63)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(29, 29, 29)
                                    .addComponent(txtsodu, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtsotien, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton9_1000, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton8_500, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton11_5000, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton10_3000, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24)))))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsodu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsotien, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7_100, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8_500, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6_200, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9_1000, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton10_3000, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jButton11_5000, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncancel)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        
        try {
            ITinhToankt server = (ITinhToankt) Naming.lookup("rmi://" + "192.168.1.3" + "/TinhToankt");
                       
            String sotienText = txtsotien.getText();  
            String gioiHanText=server.getGioiHan(stk);
            long gioiHan = Long.parseLong(gioiHanText);
            
            if(gioiHan<30000000){
                if (sotienText.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Vui lòng nhập số tiền!");
                } else {
                    long sotientext = Long.parseLong(sotienText);
                    
                  if(sotientext%10000==0){
                      if (sotientext >= 50000 && sotientext <= 5000000) {
                                
                        String soduText = txtsodu.getText();
                        long sodu = Long.parseLong(soduText);
                        long ltron=sotientext/1000;                       
                        long sotien = (ltron/10)*10;                        
                        sotien=sotien*1000;
                        
                        System.out.println(sotien);
                            
                        long sodum = sodu - sotien;

                        if (sotien > sodu) {
                            JOptionPane.showMessageDialog(this, "Số dư không đủ!");
                        } else {
                            server.setHoaDon(stk, "Rut tien tai ATM", sotien, stk);
                            server.setSoDu(stk, sodum);
                            JOptionPane.showMessageDialog(this, "Giao dịch thành công!");
                            String sdu = server.timstk(stk);
                            long gioiHanm=gioiHan+sotien;
                            server.setGioiHan(stk, gioiHanm);
                            txtsodu.setText(sdu);
                            txtsotien.setText("");
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Số tiền bạn rút phải >=50.000&&<=5.000.000!");
                    }
                      
                  }else{
                      JOptionPane.showMessageDialog(this, "Vui lòng nhập lại số tiền!");
                  }
                    
                }
            }else {
                JOptionPane.showMessageDialog(this,"Giao dịch của bạn vượt mức hạn cho phép trong ngày!");
            }
            



        } catch (Exception loi) {
            loi.printStackTrace();
        } 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        Myclientmenu f = new Myclientmenu(this.stk);
        f.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
            
                  Xuly xl=new Xuly();
                    xl.start();
    }//GEN-LAST:event_formWindowOpened

    private void txtsotienKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsotienKeyTyped
            char c=evt.getKeyChar();
            if(!Character.isDigit(c)){
                evt.consume();
            }
    }//GEN-LAST:event_txtsotienKeyTyped

    private void jButton6_200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6_200ActionPerformed
       txtsotien.setText("200000");
    }//GEN-LAST:event_jButton6_200ActionPerformed

    private void jButton9_1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9_1000ActionPerformed
       txtsotien.setText("1000000");
    }//GEN-LAST:event_jButton9_1000ActionPerformed

    private void jButton11_5000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11_5000ActionPerformed
        txtsotien.setText("5000000");
    }//GEN-LAST:event_jButton11_5000ActionPerformed

    private void jButton10_3000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10_3000ActionPerformed
        txtsotien.setText("3000000");
    }//GEN-LAST:event_jButton10_3000ActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
               try {
                ITinhToankt server = (ITinhToankt) Naming.lookup("rmi://" + "192.168.1.3" + "/TinhToankt");               
                
                int choice = JOptionPane.showConfirmDialog(
                        null,
                        "Bạn có muốn tiếp tục thực hiện giao dịch nữa không?",
                        "Xác nhận",
                        JOptionPane.YES_NO_OPTION);

                if (choice == JOptionPane.NO_OPTION) {
                    server.setTrangThaiTrue(stk);
                    System.exit(0);
                    // Thoát khỏi ứng dụng
                }               

            } catch (Exception loi) {
                loi.printStackTrace();
            }

    }//GEN-LAST:event_btncancelActionPerformed

    private void jButton7_100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7_100ActionPerformed
                txtsotien.setText("100000");
    }//GEN-LAST:event_jButton7_100ActionPerformed

    private void jButton8_500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8_500ActionPerformed
       txtsotien.setText("500000");
    }//GEN-LAST:event_jButton8_500ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Myclientruttien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Myclientruttien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Myclientruttien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Myclientruttien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Myclientruttien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10_3000;
    private javax.swing.JButton jButton11_5000;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6_200;
    private javax.swing.JButton jButton7_100;
    private javax.swing.JButton jButton8_500;
    private javax.swing.JButton jButton9_1000;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtsodu;
    private javax.swing.JTextField txtsotien;
    // End of variables declaration//GEN-END:variables
}
